apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-results-pvc
spec:
  accessModes:
    - ReadWriteMany             # Allow multiple pods to read / write
  resources:
    requests:
      storage: 500Mi