apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-modifier
  namespace: default
rules:
  # Permissions for updating deployments
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["patch", "update"]
  # Permissions for listing and getting pods
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-modifier-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: autoscaler-sa
  namespace: default
roleRef:
  kind: Role
  name: deployment-modifier
  apiGroup: rbac.authorization.k8s.io
