apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-results-pvc
spec:
  accessModes:
    - ReadWriteMany  # Allows multiple pods to read/write
  resources:
    requests:
      storage: 1Mi